### ISSUE TITLE
Идентификация диалогов

### ISSUE THREAD

**Issue by eXeGOODER** [eXeGOODER/Play4Free-SiRoP#1]
Какой способ будет лучше?
1. Обычный - вставлять цифры
Пример:
`ShowPlayerDialog(playerid, 1234, ...)`
2. Автоматические цифры, благодаря `enum`
Пример:
```pawn
enum {
 d_mainmenu,
 d_login
}

ShowPlayerDialog(playerid, d_mainmenu, ...)
```

**Comment by lJohhnyl** [comment]
Я больше использую 2 способ. Как по мне он намного лучше. Но это уже твоё решения.
