### ISSUE TITLE
Анимация во время разговора

### ISSUE THREAD

**Issue by eXeGOODER** [eXeGOODER/Play4Free-SiRoP#6]
Подобрал два варианта для обычного разговора:
1. `ApplyAnimation(playerid, "MISC", "Idle_Chat_02", 4.1, 0, 1,1, 0, 0, 1);`
2. `ApplyAnimation(playerid, "ped", "IDLE_chat", 4.1, 0, 1,1, 0, 0, 1);`
Но почему-то игрок не может двигаться во время анимации.

Какая анимация нужна для крика? (/s)

**Comment by eXeGOODER** [comment]
Во время анимации разговора, персонажа замораживает, не знаю в чём дело, может быть нужна другая анимация.
Я видел на других серверах, во время анимации можно ходить, и она совсем не мешает.
Нужна типа ваша помощь :smiley:

**Comment by lJohhnyl** [comment]
Замени на это:
`ApplyAnimation(playerid,"PED","IDLE_CHAT",8.1,0,1,1,1,1);`
